export enum ROLES {
  Harvester = 'Harvester',
  Upgrader = 'Upgrader',
  Builder = 'Builder'
}

export const EXIT_NAME = {
  [FIND_EXIT_TOP]: 'FIND_EXIT_TOP',
  [FIND_EXIT_LEFT]: 'FIND_EXIT_LEFT',
  [FIND_EXIT_BOTTOM]: 'FIND_EXIT_BOTTOM',
  [FIND_EXIT_RIGHT]: 'FIND_EXIT_RIGHT'
};

export const EXITS = [FIND_EXIT_TOP, FIND_EXIT_RIGHT, FIND_EXIT_BOTTOM, FIND_EXIT_LEFT];

export const ORDER_STRUCTURES: BuildableStructureConstant[] = [
  STRUCTURE_SPAWN,
  STRUCTURE_STORAGE,
  STRUCTURE_TOWER,
  STRUCTURE_EXTENSION,
  STRUCTURE_CONTAINER,
  STRUCTURE_LINK,
  STRUCTURE_WALL,
  STRUCTURE_EXTRACTOR,
  STRUCTURE_TERMINAL,
  STRUCTURE_LAB,
  STRUCTURE_RAMPART,
  STRUCTURE_OBSERVER,
  STRUCTURE_NUKER,
  STRUCTURE_POWER_SPAWN,
  STRUCTURE_ROAD
];
